CC=gcc
CFLAGS=-std=gnu99 -I/usr/include -I/usr/local/include -I/usr/local/include/SDL
LDFLAGS=-L/usr/lib -L/usr/local/lib -lpdl -lcjson -lSDL -Wl,-rpath-link=/usr/lib -Wl,-rpath-link=/usr/local/lib

premplayer:
